# Generated by Django 6.0.2 on 2026-04-03 09:54

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=6, unique=True, verbose_name='کد')),
                ('content', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'مورد پیست',
                'verbose_name_plural': 'موردهای پیست',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='نمایش سایت')),
                ('brand_logo', models.FileField(blank=True, help_text='بهتر است PNG/SVG با پس\u200cزمینه شفاف و عرض حداقل 320 پیکسل باشد.', null=True, upload_to=core.models.branding_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'webp', 'jpg', 'jpeg'], message='فرمت لوگو باید یکی از SVG, PNG, WEBP, JPG, JPEG باشد.')], verbose_name='لوگو هدر')),
                ('brand_icon', models.FileField(blank=True, help_text='SVG یا PNG یا ICO مربعی 64×64 یا بزرگ\u200cتر برای نمایش آیکن مرورگر.', null=True, upload_to=core.models.branding_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'ico'], message='فرمت آیکن باید یکی از SVG, PNG, ICO باشد.')], verbose_name='آیکن (favicon)')),
                ('reymit_link', models.URLField(blank=True, help_text='لینک حساب Reymit شما برای پذیرش پرداخت', verbose_name='لینک Reymit')),
                ('author_username', models.CharField(default='AnesPy', help_text='مثال: @AnesPy (بدون نماد @)', max_length=50, verbose_name='نام کاربری سازنده')),
                ('author_url', models.URLField(default='https://t.me/AnesPy', help_text='URL پروفایل یا صفحه شخصی سازنده', verbose_name='لینک پروفایل سازنده')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیم سایت',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('tron', 'Tron (TRX)'), ('litecoin', 'Litecoin'), ('ripple', 'Ripple (XRP)'), ('solana', 'Solana'), ('dogecoin', 'Dogecoin'), ('monero', 'Monero'), ('other', 'سایر')], max_length=20, verbose_name='شبکه')),
                ('address', models.TextField(verbose_name='آدرس ولت')),
                ('description', models.CharField(blank=True, help_text='مثال: Ethereum Wallet', max_length=200, verbose_name='توضیح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'ولت دونیشن',
                'verbose_name_plural': 'ولت های دونیشن',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
