# Generated by Django 6.0.2 on 2026-03-31 20:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branding_assets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasteitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'مورد پیست', 'verbose_name_plural': 'موردهای پیست'},
        ),
        migrations.AlterField(
            model_name='pasteitem',
            name='code',
            field=models.CharField(editable=False, max_length=6, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='pasteitem',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='pasteitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='pasteitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='فایل'),
        ),
    ]
