# Generated by Django 6.0.2 on 2026-03-31 20:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pasteitem_options_alter_pasteitem_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='brand_icon',
            field=models.ImageField(blank=True, help_text='PNG یا ICO مربعی 64×64 یا بزرگ\u200cتر برای نمایش آیکن مرورگر.', null=True, upload_to=core.models.branding_upload, verbose_name='آیکن (favicon)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='brand_logo',
            field=models.ImageField(blank=True, help_text='بهتر است PNG/SVG با پس\u200cزمینه شفاف و عرض حداقل 320 پیکسل باشد.', null=True, upload_to=core.models.branding_upload, verbose_name='لوگو هدر'),
        ),
    ]
