# Generated by Django 6.0.2 on 2026-04-02 08:32

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesetting_brand_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='brand_icon',
            field=models.FileField(blank=True, help_text='SVG یا PNG یا ICO مربعی 64×64 یا بزرگ\u200cتر برای نمایش آیکن مرورگر.', null=True, upload_to=core.models.branding_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'ico'], message='فرمت آیکن باید یکی از SVG, PNG, ICO باشد.')], verbose_name='آیکن (favicon)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='brand_logo',
            field=models.FileField(blank=True, help_text='بهتر است PNG/SVG با پس\u200cزمینه شفاف و عرض حداقل 320 پیکسل باشد.', null=True, upload_to=core.models.branding_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'webp', 'jpg', 'jpeg'], message='فرمت لوگو باید یکی از SVG, PNG, WEBP, JPG, JPEG باشد.')], verbose_name='لوگو هدر'),
        ),
    ]
