# Generated by Django 6.0.2 on 2026-04-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sitesetting_brand_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('tron', 'Tron (TRX)'), ('litecoin', 'Litecoin'), ('ripple', 'Ripple (XRP)'), ('solana', 'Solana'), ('dogecoin', 'Dogecoin'), ('monero', 'Monero'), ('other', 'سایر')], max_length=20, verbose_name='شبکه')),
                ('address', models.TextField(verbose_name='آدرس ولت')),
                ('description', models.CharField(blank=True, help_text='مثال: Ethereum Wallet', max_length=200, verbose_name='توضیح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'ولت دونیشن',
                'verbose_name_plural': 'ولت های دونیشن',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='remit_link',
            field=models.URLField(blank=True, help_text='لینک حساب Remit شما برای پذیرش پرداخت', verbose_name='لینک Remit'),
        ),
    ]
